import type { CatalogObject } from "./projects";

export const starterCatalog: CatalogObject[] = [
  {
    id: "furniture-sofa",
    sku: "FURN-001",
    name: "Sofa",
    category: "furniture",
    placementMode: "floor-mounted",
    defaultDimensions: { width: 2.1, height: 0.85, depth: 0.9, unit: "m" },
    allowedSurfaceKinds: ["floor"],
    tags: ["furniture", "seating", "living-room"],
    representation: "sofa",
    description: "Approximate sofa volume for furniture layout studies.",
  },
  {
    id: "furniture-armchair",
    sku: "FURN-002",
    name: "Armchair",
    category: "furniture",
    placementMode: "floor-mounted",
    defaultDimensions: { width: 0.9, height: 0.9, depth: 0.9, unit: "m" },
    allowedSurfaceKinds: ["floor"],
    tags: ["furniture", "seating"],
    representation: "chair",
  },
  {
    id: "furniture-dining-table",
    sku: "FURN-003",
    name: "Dining Table",
    category: "furniture",
    placementMode: "floor-mounted",
    defaultDimensions: { width: 1.8, height: 0.76, depth: 0.95, unit: "m" },
    allowedSurfaceKinds: ["floor"],
    tags: ["furniture", "table", "dining-room"],
    representation: "table",
  },
  {
    id: "furniture-bed-queen",
    sku: "FURN-004",
    name: "Queen Bed",
    category: "furniture",
    placementMode: "floor-mounted",
    defaultDimensions: { width: 1.6, height: 0.65, depth: 2.1, unit: "m" },
    allowedSurfaceKinds: ["floor"],
    tags: ["furniture", "bedroom"],
    representation: "bed",
  },
  {
    id: "electrical-outlet-duplex",
    sku: "ELEC-001",
    name: "Duplex Outlet",
    category: "electrical",
    placementMode: "wall-mounted",
    defaultDimensions: { width: 0.08, height: 0.12, depth: 0.04, unit: "m" },
    defaultClearance: { width: 0.3, height: 0.3, depth: 0.2, unit: "m" },
    allowedSurfaceKinds: ["wall"],
    tags: ["power", "receptacle", "finish"],
    description: "Standard duplex receptacle for early layout planning.",
  },
  {
    id: "electrical-switch-single",
    sku: "ELEC-002",
    name: "Single Pole Switch",
    category: "electrical",
    placementMode: "wall-mounted",
    defaultDimensions: { width: 0.08, height: 0.12, depth: 0.04, unit: "m" },
    allowedSurfaceKinds: ["wall"],
    tags: ["switch", "lighting"],
  },
  {
    id: "electrical-panel-small",
    sku: "ELEC-003",
    name: "Electrical Panel",
    category: "electrical",
    placementMode: "wall-mounted",
    defaultDimensions: { width: 0.4, height: 0.9, depth: 0.15, unit: "m" },
    defaultClearance: { width: 0.9, height: 2, depth: 1, unit: "m" },
    allowedSurfaceKinds: ["wall"],
    tags: ["panel", "service"],
  },
  {
    id: "thermostat-standard",
    sku: "HVAC-001",
    name: "Thermostat",
    category: "hvac",
    placementMode: "wall-mounted",
    defaultDimensions: { width: 0.12, height: 0.12, depth: 0.04, unit: "m" },
    allowedSurfaceKinds: ["wall"],
    tags: ["controls", "temperature"],
  },
  {
    id: "hvac-register-ceiling",
    sku: "HVAC-002",
    name: "Ceiling Register",
    category: "hvac",
    placementMode: "ceiling-mounted",
    defaultDimensions: { width: 0.3, height: 0.02, depth: 0.3, unit: "m" },
    allowedSurfaceKinds: ["ceiling"],
    tags: ["air", "supply"],
  },
  {
    id: "security-camera-dome",
    sku: "LV-001",
    name: "Dome Camera",
    category: "low-voltage",
    placementMode: "ceiling-mounted",
    defaultDimensions: { width: 0.14, height: 0.1, depth: 0.14, unit: "m" },
    allowedSurfaceKinds: ["ceiling", "wall"],
    tags: ["security", "camera"],
  },
  {
    id: "smoke-detector-round",
    sku: "LS-001",
    name: "Smoke Detector",
    category: "life-safety",
    placementMode: "ceiling-mounted",
    defaultDimensions: { width: 0.12, height: 0.05, depth: 0.12, unit: "m" },
    allowedSurfaceKinds: ["ceiling"],
    tags: ["alarm", "safety"],
  },
  {
    id: "conduit-straight-section",
    sku: "ELEC-004",
    name: "Conduit Section",
    category: "electrical",
    placementMode: "wall-mounted",
    defaultDimensions: { width: 1, height: 0.03, depth: 0.03, unit: "m" },
    allowedSurfaceKinds: ["wall", "ceiling"],
    tags: ["raceway", "routing"],
  },
  {
    id: "pipe-section-basic",
    sku: "PLUMB-001",
    name: "Pipe Section",
    category: "plumbing",
    placementMode: "free-place",
    defaultDimensions: { width: 1, height: 0.05, depth: 0.05, unit: "m" },
    allowedSurfaceKinds: ["wall", "ceiling", "floor", "unknown"],
    tags: ["pipe", "routing"],
  },
  {
    id: "access-panel",
    sku: "ARCH-001",
    name: "Access Panel",
    category: "architectural",
    placementMode: "wall-mounted",
    defaultDimensions: { width: 0.35, height: 0.35, depth: 0.03, unit: "m" },
    allowedSurfaceKinds: ["wall", "ceiling"],
    tags: ["service", "architectural"],
  },
];
